services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
      RPC_LISTEN_PORT: "8545"
      RPC_SERVER_NAME: "_"
      TATUM_URL: "https://avax-mainnet.gateway.tatum.io/"
      TATUM_API_KEY: ${TATUM_API_KEY}
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
      - target: 8545
        published: 8545