version: '3.9'

services:
  user-ops-indexer:
    image: ghcr.io/blockscout/user-ops-indexer:${USER_OPS_INDEXER_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'user-ops-indexer'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-user-ops-indexer.env
    environment:
      - USER_OPS_INDEXER__INDEXER__RPC_URL=https://rpc.ankr.com/arbitrum/8c80382706a34796c6fa731849f34851b2e1f983ec2880f4b779da9f0c9932c3
      - USER_OPS_INDEXER__DATABASE__CONNECT__URL=${USER_OPS_INDEXER__DATABASE__CONNECT__URL:-postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout}
      - USER_OPS_INDEXER__DATABASE__RUN_MIGRATIONS=true
